chore: FormatとLintとBuildテストをするCIを整備
ricora/alg.tus-ricora.com pull request #12
Opened 2023-12-26 08:41 UTC by sou1118

2023-12-26 10:19 UTC, r4ai commented on .github/workflows/ci.yml
> +        run: bun install
```suggestion
        run: bun install --frozen-lockfile
```

> "For reproducible installs, use --frozen-lockfile. This will install the exact versions of each package specified in the lockfile. If your package.json disagrees with bun.lockb, Bun will exit with an error. The lockfile will not be updated."
> https://bun.sh/docs/cli/install#production-mode

2023-12-26 10:19 UTC, r4ai commented on .github/workflows/ci.yml
> +        run: bun install
```suggestion
        run: bun install --frozen-lockfile
```

2023-12-26 10:19 UTC, r4ai commented on .github/workflows/ci.yml
> +      - name: Install dependencies
```suggestion
        run: bun install --frozen-lockfile
```

2023-12-26 10:19 UTC, r4ai commented on .github/workflows/ci.yml
> +        run: bun format
```suggestion
        run: bun format:check
```

`format`スクリプトは`rettier --ignore-path .gitignore --write . --cache`であり、フォーマットの修正用スクリプトなので、フォーマットのチェックはしません。よって、新しく以下のような`format:check`スクリプトを作成してそれを使うべきだと思います。

`package.json`:
```json
{
  "scripts": {
    "format:check": "prettier --ignore-path .gitignore --check . --cache"
  }
}
```

2023-12-26 10:24 UTC, r4ai commented on .github/workflows/ci.yml
> +        run: bun install
```suggestion
        run: bun install --frozen-lockfile
```

2023-12-27 12:43 UTC, 3w36zj6 requested changes

2023-12-27 12:43 UTC, 3w36zj6 commented on .github/workflows/ci.yml
ビルドテストのコマンドだけが`run`を省略せず`bun run build`になっているのは、組み込みの`bun build`との衝突防止のためだと思われますが、フォーマットとリントについてもBunの組み込みコマンドでないことを強調するために`bun run`で記述し、コマンドの形式を統一した方が良いかと思われます。

2023-12-27 12:46 UTC, r4ai commented on .github/workflows/ci.yml
今後組み込みコマンドが増える可能性もあるので、私も`bun run`で記述するべきだと思います。

2023-12-28 02:01 UTC, r4ai approved these changes
LGTM

2023-12-28 03:49 UTC, 3w36zj6 approved these changes

2023-12-28 03:50 UTC, merged