docs: "RICORAのMDX記法一覧"を作成
ricora/alg.tus-ricora.com pull request #131
Opened 2024-02-16 04:11 UTC by r4ai

## 変更点

- `src/content/pages/mdx-guide`に"RICORAのMDX記法一覧"を執筆した

## 確認事項

- `/mdx-guide`で"RICORAのMDX記法一覧"が表示されること
- 書き忘れている内容、分かりにくい表現、誤りなどがないか

2024-02-16 06:09 UTC, 3w36zj6 requested changes

2024-02-16 06:09 UTC, 3w36zj6 commented on src/content/pages/mdx-guide/index.mdx
> +  </div>
HTMLの見出しは`h6`まで存在するので、すべて明記しておくと良いと思います。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/Heading_Elements

```suggestion
  <div slot="left">
    ```mdx
    # 見出し1
    ## 見出し2
    ### 見出し3
    #### 見出し4
    ##### 見出し5
    ###### 見出し6
    ```
  </div>
  <div slot="right">
    # 見出し1
    ## 見出し2
    ### 見出し3
    #### 見出し4
    ##### 見出し5
    ###### 見出し6
  </div>
```

ただし、このプロジェクト内において下位の見出しの使用を推奨していないという場合は、追加でその旨を明記しておくと良いと思います。

2024-02-16 06:09 UTC, 3w36zj6 commented on src/content/pages/mdx-guide/index.mdx
> +> アクセシビリティの観点から、見出しはレベル2から始めてください。
MarkdownはHTMLのサブセットであり、HTMLの慣例に倣うべきであるからという説明があると良いと思います。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/Heading_Elements#1_つのページに複数の_h1_要素を使用しない

また、見出し1はページの内容を説明する要素として文章の先頭に置くのが一般的であるということにも触れておくと良いと思います。

2024-02-16 06:09 UTC, 3w36zj6 commented on src/content/pages/mdx-guide/index.mdx
こちらに移行して不要になった`/posts/hello-world-v2`にある記法一覧を消しておいてください。

2024-02-16 06:09 UTC, 3w36zj6 commented on src/content/pages/mdx-guide/index.mdx
> +title: RICORAのMDX記法一覧
```suggestion
title: 本サイトで利用可能なMDX記法一覧
```

2024-02-17 06:59 UTC, 3w36zj6 requested changes

2024-02-17 06:59 UTC, 3w36zj6 commented on src/content/pages/mdx-guide/index.mdx
> +> 見出し5, 6は、一般的には使用されません。見出しのレベルが深くなると、文書の構造が複雑になり、読みにくくなるためです。
少し主観的な表現になってしまっているので、`h5`, `h6`のスタイルは[@tailwindcss/typography](https://tailwindcss.com/docs/typography-plugin)で意図的に実装されていないからという説明があると良いと思います。

https://github.com/tailwindlabs/tailwindcss-typography/issues/262

2024-02-17 06:59 UTC, 3w36zj6 commented on src/content/pages/mdx-guide/index.mdx
> +
カテゴリと同様に、タグの説明があると良いと思います。

2024-02-17 09:50 UTC, 3w36zj6 approved these changes
:ok:?

2024-02-17 10:15 UTC, sou1118 approved these changes
:ok:

2024-02-17 11:09 UTC, merged