feat: devcontainerを実行するための設定ファイルを作成
ricora/alg.tus-ricora.com pull request #132
Opened 2024-02-16 14:37 UTC by sou1118

close #15

2024-02-16 15:26 UTC, 3w36zj6 requested changes

2024-02-16 15:26 UTC, 3w36zj6 commented on .devcontainer/devcontainer.json
> +  "name": "Bun",
`name`にはプロジェクトにちなんだ名前を設定すると良いと思います。

https://containers.dev/implementors/json_reference/

```suggestion
  "name": "alg.tus-ricora.com",
```

2024-02-16 15:26 UTC, 3w36zj6 commented on .devcontainer/Dockerfile
`.tool-versions`にあるバージョンのBunを使うようにしてください。[mise](https://github.com/jdx/mise)を使用すると良いと思います。

2024-02-17 11:28 UTC, r4ai approved these changes
LGTM!

2024-02-17 11:35 UTC, r4ai approved these changes
間違えてApproveを消してしまったので再度

2024-02-17 12:26 UTC, sou1118 commented
![image](https://github.com/ricora/alg-blog/assets/48943030/4792cf7a-8498-4a7b-a10c-56a505ae8544)

2024-02-17 12:32 UTC, r4ai approved these changes
🆗

2024-02-17 12:33 UTC, 3w36zj6 approved these changes

2024-02-17 12:43 UTC, merged