feat: トップページのベースを実装
ricora/alg.tus-ricora.com pull request #138
Opened 2024-02-18 07:31 UTC by 3w36zj6

close https://github.com/ricora/alg-blog/issues/46

## 変更点

トップページの内容を以下のように変更する。

- 団体の概要
- 最新記事のピックアップ
- お問い合わせ

2024-02-18 07:47 UTC, sou1118 commented on src/pages/index.astro
> +    linkTitle: "もっと詳しく見る",
「低レイヤ領域の開発から競技プログラミング、ゲーム製作、Web開発など多岐にわたり活動を行っています。」を追加しました。

2024-02-18 07:49 UTC, sou1118 commented on src/pages/index.astro
> +      "RICORA Programming Teamは東京理科大学 野田キャンパスにて活動するプログラミングサークルです。活動内容活動内容活動内容活動内容活動内容活動内容活動内容活動内容活動内容。",
```suggestion
      "RICORA Programming Teamは東京理科大学 野田キャンパスにて活動するプログラミングサークルです。低レイヤ領域の開発から競技プログラミング、ゲーム製作、Web開発など多岐にわたり活動を行っています。",
```

2024-02-18 07:59 UTC, sou1118 commented on src/pages/index.astro
> +    description: "依頼依頼依頼依頼依頼依頼依頼依頼依頼依頼依頼依頼依頼依頼入部入部入部入部入部入部入部。",
```suggestion
    description: "依頼や質問、入部についてはこちらからお願いします。（Google Formに飛びます）",
```

2024-02-20 14:17 UTC, sou1118 approved these changes

2024-02-20 15:34 UTC, r4ai requested changes

2024-02-20 15:34 UTC, r4ai commented on src/pages/index.astro
> +    headerIcon: "twemoji:desktop-computer",
```suggestion
    headerIcon: "fluent-emoji-flat:desktop-computer",
```

他の個所で絵文字にはFluent Emojiを利用しているので、合わせた方が良いかなと思いました。

2024-02-20 15:34 UTC, r4ai commented on src/pages/index.astro
> +    headerIcon: "twemoji:newspaper",
```suggestion
    headerIcon: "fluent-emoji-flat:newspaper",
```

2024-02-20 15:34 UTC, r4ai commented on src/pages/index.astro
> +    headerIcon: "twemoji:handshake",
```suggestion
    headerIcon: "fluent-emoji-flat:handshake",
```

2024-02-20 15:34 UTC, r4ai commented on src/pages/index.astro
> +              >
```suggestion
                class="flex flex-row items-center justify-center rounded-lg border bg-zinc-50 px-5 py-2.5 text-center transition hover:bg-zinc-200/50 dark:bg-zinc-950 dark:hover:bg-zinc-900"
```

`hover:brightness-90`だと、ダークモード時にホバーをしても色が変わりづらいため、`dark:hover:bg-zinc-900`に変更し、それに伴い背景色を調整した方が良いかなと思ったのですが、どう思いますか？

2024-02-20 15:34 UTC, r4ai commented on src/pages/index.astro
> +
```suggestion
              <p class="my-6 md:text-lg text-muted-foreground">{content.description}</p>
```

- 薄めの文字色としては、他の個所の多くで`text-muted-foreground`を使用しているため、それに合わせた方が良いかなと思いました。
- スマホ画面だと`text-lg`は大きすぎるように感じたので、`md:text-lg`に変更した方が良いかなと思いました。

2024-02-20 15:34 UTC, r4ai commented on src/pages/index.astro
> +                  <span>{content.headerTitle}</span>
```suggestion
              <h2 class="flex flex-row items-center text-2xl font-black md:text-4xl gap-4 md:gap-6">
                <>
                  <Icon name={content.headerIcon} class="w-10 flex-none md:w-12" />
```

アイコンの左側には余白がないほうが整列している印象を受けて良いかなと思ったのですが、どうでしょうか？私自身デザインセンスがなくこの感覚が正しいのか分からないので、全然無視していただいても構いません。

2024-02-20 15:40 UTC, r4ai requested changes
前回のRequest changesで一部の変更リクエストの行指定がおかしかったので、修正版です。

2024-02-20 15:40 UTC, r4ai commented on src/pages/index.astro
> +                  <Icon name={content.headerIcon} class="w-24 flex-none p-4 md:w-28 md:p-6" />
```suggestion
              <h2 class="flex flex-row items-center text-2xl font-black md:text-4xl gap-4 md:gap-6">
                <>
                  <Icon name={content.headerIcon} class="w-10 flex-none md:w-12" />
```

アイコンの左側には余白がないほうが整列している印象を受けて良いかなと思ったのですが、どうでしょうか？私自身デザインセンスがなくこの感覚が正しいのか分からないので、全然無視していただいても構いません。

2024-02-20 15:40 UTC, r4ai commented on src/pages/index.astro
> +              <p class="my-6 text-lg text-gray-500">{content.description}</p>
```suggestion
              <p class="my-6 md:text-lg text-muted-foreground">{content.description}</p>
```

- 薄めの文字色としては、他の個所の多くで`text-muted-foreground`を使用しているため、それに合わせた方が良いかなと思いました。
- スマホ画面だと`text-lg`は大きすぎるように感じたので、`md:text-lg`に変更した方が良いかなと思いました。

2024-02-20 15:40 UTC, r4ai commented on src/pages/index.astro
> +                class="flex flex-row items-center justify-center rounded-lg border border-gray-300 bg-gray-50 px-5 py-2.5 text-center transition hover:brightness-90 dark:border-gray-700 dark:bg-gray-
```suggestion
                class="flex flex-row items-center justify-center rounded-lg border bg-zinc-50 px-5 py-2.5 text-center transition hover:bg-zinc-200/50 dark:bg-zinc-950 dark:hover:bg-zinc-900"
```

`hover:brightness-90`だと、ダークモード時にホバーをしても色が変わりづらいため、`dark:hover:bg-zinc-900`に変更し、それに伴い背景色を調整した方が良いかなと思ったのですが、どう思いますか？

2024-02-20 16:28 UTC, r4ai approved these changes
🆗

2024-02-20 16:29 UTC, merged