feat: フッターを追加
ricora/alg.tus-ricora.com pull request #156
Opened 2024-02-22 13:38 UTC by sou1118

close #147

2024-02-22 14:14 UTC, r4ai commented
デスクトップ画面でページの下部までスクロールした際に、NavBarが上に上がってしまうので、NavBarの右側の本体部分の下部にフッターを表示するようにした方が良いと思われます。

2024-02-22 14:20 UTC, r4ai commented
`BaseLayout.astro`の`<slot />`部分を、以下のようにすると良いと思います
```astro
<div class="flex flex-col gap-8"> {/* gapの値は適当に書いているので、良い感じに調整してください */}
  <slot />
  {/* フッターのコード */}
</div>
```

2024-02-22 14:40 UTC, r4ai requested changes

2024-02-22 14:40 UTC, r4ai commented on src/layouts/BaseLayout/BaseLayout.astro
> +      <div class="flex flex-col gap-8">
```suggestion
      <div class="flex flex-col gap-8 flex-1">
```
記事のページで記事の部分が中央に来ていないので、修正すると良いと思います

2024-02-23 01:19 UTC, r4ai approved these changes
LGTM!

2024-02-23 06:03 UTC, 3w36zj6 approved these changes

2024-02-23 06:03 UTC, merged