chore: LICENSEを追加
ricora/alg.tus-ricora.com pull request #241
Opened 2024-03-16 14:29 UTC by r4ai

#230 

- MITラインセスに"ブランディングや記事等の文章ファイルについてはこれに含まれず、PRを投げることを目的とした複製や改変のみを認める"旨を追加したライセンスを追加

## 確認事項

- OSSライセンスについて全く分からないので、これで良いのか確認して頂きたい

2024-03-16 14:45 UTC, 3w36zj6 requested changes

2024-03-16 14:45 UTC, 3w36zj6 commented on LICENSE
> +the prior written consent of RICORA.
原文と書式を合わせるために、段落内の改行を削除してください。

2024-03-16 14:45 UTC, 3w36zj6 commented on README.md
> +このリポジトリは[MIT License](./LICENSE)の下で公開されています。ただし、ブランディングや記事等の文章ファイルについてはこれに含まれず、PRを投げることを目的とした複製や改変のみを認めます。
「PRを投げる」が口語調なので、公式で使われている日本語表記に合わせた方が良いと思います。

https://docs.github.com/ja/pull-requests

2024-03-16 16:00 UTC, 3w36zj6 requested changes

2024-03-16 16:00 UTC, 3w36zj6 commented on LICENSE
> +
```suggestion
MIT License

Copyright 2024 RICORA

```

2024-03-16 16:00 UTC, 3w36zj6 commented on README.md
> +## 📄 LICENSE
```suggestion
## ⚖️ License
```

2024-03-16 16:00 UTC, 3w36zj6 commented on README.md
> +このリポジトリは[MIT License](./LICENSE)の下で公開されています。ただし、ブランディングや記事等の文章ファイルについてはこれに含まれず、pull requestを使ったプロジェクトへの変更の提案を目的とした複製や改変のみを認めます。
```suggestion
  このリポジトリは[MIT License](./LICENSE)の下で公開されています。**ただし、ロゴや組織名称等のブランディング、記事等の文章ファイルはMIT Licenseの適用範囲に含まれていないことに注意してください。これらのファイルについては、[Pull requestによる変更の提案](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests)を目的とした複製や改変のみを認めます。**
```

2024-03-16 16:20 UTC, 3w36zj6 approved these changes

2024-04-06 05:19 UTC, sou1118 commented on LICENSE
> +Copyright 2024 RICORA
ホームページ上のコピーライトと合わせた方が良いかと思われます。
```suggestion
Copyright 2024 RICORA Programming Team
```

2024-04-06 05:19 UTC, sou1118 commented on LICENSE
> +Notwithstanding the above permission to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so
```suggestion
Notwithstanding the above permission to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, no license is granted hereunder to use, copy, modify, or distribute any trademarks, service marks, branding, or articles associated with RICORA for any purpose without the prior written consent of RICORA Programming Team.
```

2024-04-06 07:09 UTC, sou1118 approved these changes

2024-04-06 07:09 UTC, merged