docs: ディレクトリ構造の説明を追加
ricora/alg.tus-ricora.com pull request #332
Opened 2024-05-20 05:54 UTC by r4ai

close #97

## 確認事項

- 誤字脱字やわかりにくい表現がないか
- 他に記述すべき内容がないか

2024-05-20 11:43 UTC, 3w36zj6 requested changes

2024-05-20 11:43 UTC, 3w36zj6 commented on ARCHITECTURE.md
> +| `src/layouts`             | 複数ページで共通のレイアウトを定義する                                         |
IMO: Directoryは辞書順でソートされていたほうが良いかもしれないと思いました。

2024-05-20 11:43 UTC, 3w36zj6 commented on ARCHITECTURE.md
> +| `src/content/members`     | RICORA Programming Teamのメンバー情報を格納する                                |
```suggestion
| `src/content/members`     | メンバー一覧ページで使われるメンバー情報を格納する                                |
```

IMO: 「RICORA Programming Teamの」であることは明らかなので、他の説明文と比較すると不要かなと思いました。

2024-05-20 11:43 UTC, 3w36zj6 commented on ARCHITECTURE.md
> +| `src/components/ui`       | ParkUI によって生成されるコンポーネントを格納する                              |
```suggestion
| `src/components/ui`       | ParkUIによって生成されるコンポーネントを格納する                              |
```

([textlint-rule-ja-space-between-half-and-full-width](https://github.com/textlint-ja/textlint-rule-preset-ja-spacing/tree/master/packages/textlint-rule-ja-space-between-half-and-full-width)に従うのであれば、)不要なスペースがあります。

2024-05-20 11:43 UTC, 3w36zj6 commented on ARCHITECTURE.md
> +`src/content/members`ディレクトリでは、RICORA Programming Teamのメンバー情報を格納します。
```suggestion
`src/content/members`ディレクトリでは、メンバー一覧ページで使われるメンバー情報を格納します。
```

表の説明文と同様です。

2024-05-20 11:43 UTC, 3w36zj6 commented on ARCHITECTURE.md
> +# Architecture
日本語周りにおけるスペースの有無を統一する必要がありそうです。

https://github.com/textlint-ja/textlint-rule-preset-ja-spacing

2024-05-21 08:09 UTC, r4ai commented
全角文字と空白文字の間のスペース削除には以下の正規表現を利用した

- `s/(\w+)\s([^\x00-\x7F])/$1$2/g`
- `s/([^\x00-\x7F])\s(\w+)/$1$2/g`

2024-05-21 14:47 UTC, 3w36zj6 approved these changes
:ok:?

2024-05-21 23:48 UTC, sou1118 approved these changes
:ok:

2024-05-21 23:48 UTC, merged