chore: Huskyとlint-stagedをLefthookに移行
ricora/alg.tus-ricora.com pull request #362
Opened 2024-06-16 02:04 UTC by 3w36zj6

close #361

## 変更点

- 依存関係のhuskyとlint-staged及び設定ファイルを削除した
- 依存関係にlefthookを追加しlint-stagedの設定を移行した

## 確認事項

- Huskyとlint-stagedに関連する変更がすべて削除されている
- Lefthookのセットアップが利用できる
- pre-commitが利用できる

## 備考

ローカル環境のGit Hooksは以下のコマンドで削除できる。

```sh
git config --unset core.hooksPath
```

2024-06-17 12:48 UTC, r4ai requested changes

2024-06-17 12:48 UTC, r4ai commented on lefthook.yml
> +    prettier:
Lefthookは暗黙的に変更されたファイルをステージしないので、修正後のファイルをステージするように明示的に指定するようお願いします

ref: https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#stage_fixed

2024-06-18 07:07 UTC, r4ai approved these changes
LGTM

2024-06-18 08:16 UTC, sou1118 approved these changes
:ok:

2024-06-18 08:16 UTC, merged