docs: READMEを整備
ricora/alg.tus-ricora.com pull request #94
Opened 2024-02-03 04:00 UTC by r4ai

close #80 

- 具体的な記事の書き方やブランチの命名規則などは、wikiやCONTRIBUTIONに書くためREADMEに含めていない
- 基礎的なコマンドや必要な実行環境などについてのみ記載した

2024-02-03 04:00 UTC, r4ai commented
このほかに書くべき内容があるか教えていただけるとありがたいです。

2024-02-22 12:54 UTC, r4ai commented
Astroのconfigからだと出来なさそうなので閉じる

2024-02-23 08:22 UTC, sou1118 approved these changes

2024-02-24 06:52 UTC, 3w36zj6 requested changes

2024-02-24 06:52 UTC, 3w36zj6 commented on README.md
> +# alg.tus-ricora.com (WIP)
```suggestion
# alg.tus-ricora.com
```

2024-02-24 06:52 UTC, 3w36zj6 commented on README.md
> +> このリポジトリは現在開発中です。
```suggestion
```

2024-02-24 06:52 UTC, 3w36zj6 commented on README.md
> +- [Ark UI](https://ark-ui.com/)
変更があったと思うので最新の状態に更新してください。

2024-02-24 06:52 UTC, 3w36zj6 commented on README.md
> +生成したブログ記事は、[alg.tus-ricora.com/posts](https://alg.tus-ricora.com/posts)にて公開されます。
各記事を取得できるエンドポイントはありますが、`/posts`は現状では実装されていないので、表現を変更する必要がありそうです。

2024-02-24 06:52 UTC, 3w36zj6 commented on README.md
> +`src/content/pages/about-us/`にあるMDXファイルを基に、サークルの紹介ページを[alg.tus-ricora.com/about-us](https://alg.tus-ricora.com/about-us)にて公開します。
近日中に`/about`に変更予定なので、予めこちらも変更しておくと良いと思います。

2024-02-24 06:52 UTC, 3w36zj6 commented on README.md
> +このリポジトリは[RICORA Programming Team](https://alg.tus-ricora.com/)のブログを管理するためのものです。ブログの編集やローカルでの閲覧方法についてはWikiを参照してください。
```suggestion
このリポジトリでは[RICORA Programming Team](https://alg.tus-ricora.com/)のWebサイトを管理しています。
```

2024-02-24 06:52 UTC, 3w36zj6 commented on README.md
> +<!-- TODO: Wikiのリンクを張る -->
```suggestion
<!-- TODO: CONTRIBUTING.mdへの誘導を追加する -->

2024-02-24 11:08 UTC, 3w36zj6 requested changes

2024-02-24 11:08 UTC, 3w36zj6 commented on README.md
> +生成したブログ記事は、`alg.tus-ricora.com/posts`以下にて公開します。公開中のブログ記事一覧は、[alg.tus-ricora.com/archives](https://alg.tus-ricora.com/archives)にて確認できます。
表現を他の見出しと統一させると良いと思います。

```suggestion
### Posts

`src/content/posts/`以下にあるMDXファイルを基に、記事ページを`alg.tus-ricora.com/posts`以下にて公開します。公開中の記事一覧は、[alg.tus-ricora.com/archives](https://alg.tus-ricora.com/archives)にて確認できます。
```

2024-02-24 14:23 UTC, 3w36zj6 approved these changes

2024-02-24 14:31 UTC, merged